### ISSUE TITLE
current page not updated

### ISSUE THREAD

**Issue by nagyrobi** [dgomes/hasp-lvgl-custom-component#19]
Current page number should be also updated from `hasp/plate/state/page` (and maybe `hasp/plate/state/statusupdate`) because it looses sync if someone changes page from HA for example:

```yaml
- alias: lanbon-back-to-page-1-after-5min
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.plate_idle
      from: 'off'
      for: "00:05:00"
  action:
    - service: number.set_value
      data:
        value: '1'
      target:
        entity_id: number.plate_page
```
if the page was left at 3 when the automation above runs and sets the page on hasp-lvgl back to 1, when somebody touches the next page button, it will jump directly to page 4.
