### ISSUE TITLE
load_pages service doesn't load the file correctly

### ISSUE THREAD

**Issue by nagyrobi** [dgomes/hasp-lvgl-custom-component#26]
This is my config file for Lanbon L8 and hasp-lvgl 0.4.0: [pages_v0.jsonl](https://github.com/dgomes/hasp-lvgl-custom-component/files/6218051/pages_v0.jsonl.txt)

If I load it using the service:
```
service: hasp_lvgl.load_pages
data:
  path: /config/hasp-lvgl/pages_v0.jsonl
target:
  entity_id: hasp_lvgl.lanbon_teszt
```
Result is:
![kép](https://user-images.githubusercontent.com/1550668/112767861-55067200-9019-11eb-936b-876fc1c70539.png)

If I upload it through the web page of the plate and reboot it, everything is fine.
Tried removing the comments, blank lines etc. no difference.
