### ISSUE TITLE
Create cover control with feedback

### ISSUE THREAD

**Issue by nagyrobi** [dgomes/hasp-lvgl-custom-component#6]
Cover control with 3 buttons in hasp-lvgl:
![kép](https://user-images.githubusercontent.com/1550668/110114812-788d2280-7db5-11eb-9c3c-c1be0cf448e0.png)
It's made of 3 buttons with `"toggle":false`. But, there's no feedback on the state of the cover, as the buttons only trigger with `event`.

Same in Lovelace:
![kép](https://user-images.githubusercontent.com/1550668/110114980-b68a4680-7db5-11eb-9efb-ae16870030db.png)
Here the extra icon shows if it's moving or not and displays closed or opened icon.

The goal would be to have this kind of information hasp-lvgl too. For example support toggled buttons and keep it pressed while the cover moves up or down. Also a way to show if it's opened or closed on the middle button somehow (percentage is available in HA state of the cover).

**Comment by dgomes** [comment]
I think this falls out of scope... it's not hasp-lvgl task to keep track of covers state...

**Comment by nagyrobi** [comment]
Yes but it should display it so the custom component could do this.

**Comment by dgomes** [comment]
This would be feature creep from the custom_integration point of view... Lights (backlight, moonlight) are part of the device... but covers are not...

**Comment by fvanroie** [comment]
I think this is already advanced territory, while the basics still need to be addressed first.
IMHO we need to focus on the buttons and labels first, as that is the most basic functionality.

By combining basic objects a similar result might be achieved without special handling, but the user might need to create a cover_state or a cover_icon entity or helper that can easily be picked up by the component to display on the device.

**Comment by nagyrobi** [comment]
Yes yes I'm just pouring the ideas out. We can figure out how to do it later on the todo list...

**Comment by nagyrobi** [comment]
Can be done since https://github.com/dgomes/hasp-lvgl-custom-component/commit/a1f5704fc1a71e0e6188f796e5e2b34e98c190c4 witth plate config example:
```
{"obj":"btn","id":4,"x":5,"y":140,"w":73,"h":60,"toggle":false,"text":"\uF077","text_font":28}
{"obj":"btn","id":5,"x":83,"y":140,"w":73,"h":60,"toggle":false,"text":"\uF04C","text_font":28}
{"obj":"btn","id":6,"x":161,"y":140,"w":73,"h":60,"toggle":false,"text":"\uF078","text_font":28}
```
and component config example:
```yaml
      - obj: "p1b4"
        properties:
          "text_color": "{{ '#FFFF00' if states('cover.mycover') == 'opening' else '#FFFFFF' }}"
        event:
          "down":
            service: cover.open_cover
            target:
              entity_id: "cover.mycover"
      - obj: "p1b5"
        event:
          "down":
            service: cover.stop_cover
            target:
              entity_id: "cover.mycover"
      - obj: "p1b6"
        properties:
          "text_color": "{{ '#FFFF00' if states('cover.mycover') == 'closing' else '#FFFFFF' }}"
        event:
          "down":
            service: cover.close_cover
            target:
              entity_id: "cover.mycover"
```
Thank you for the implementation!
